### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by contigo-mr**
Fixed the "require"-declaration matching the actual repository name.

### CODE REVIEW

**Comment by AllanJard** [comment]
I'm not sure that is right. The core jQuery UI integration for DataTables has:

> `"name": "datatables.net/datatables.net-jqui",`

https://github.com/DataTables/Dist-DataTables-jQueryUI/blob/master/composer.json

Changing to `-ju` would break things.

**Comment by contigo-mr** [comment]
I guess then either the name of the main repo itself, or the declared name of the main repo within all of your jQuery-UI-styled-specific repos, is faulty. Composer is unable to resolve the names here:

> `> composer require datatables.net/datatables.net-buttons-jqui`
```powershell
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires datatables.net/datatables.net-buttons-ju * -> satisfiable by datatables.net/datatables.net-buttons-ju[3.0.0, 3.0.1, 3.0.2].
    - datatables.net/datatables.net-buttons-ju[3.0.0, ..., 3.0.2] require datatables.net/datatables.net-jqui >=1.12.1 -> could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

``` 

There is no package with the name `datatables.net/datatables.net-jqui` [[^](https://packagist.org/packages/datatables.net/datatables.net-jqui)] on packagist, 'cause its called `datatables.net/datatables.net-ju` [[^](https://packagist.org/packages/datatables.net/datatables.net-ju)]


Or am I missing something obvious here?

**Comment by AllanJard** [comment]
Sorry - it looks like I hadn't actually published the `-jqui` packages on packagist. They are present now.

**Comment by contigo-mr** [comment]
Thank you very much! It's working now. Closing here :)

**Pull request closed without merging**
